my_site/urls.py
from django.urls import path, register_converter, include
from django.http import HttpResponseNotFound
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('valutes/', include('valutes.urls')),
    path('blog/', include('valutesBlog.urls')),
    path('system/', include('system_pages.urls')),
    path('', RedirectView.as_view(url='valutes/', permanent=True)),
    path('', include('valutesBlog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель управления"
admin.site.index_title = "Сайт обзора валют"

system_pages/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "system_pages"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('logout/', views.logout_user, name='login'),

    path('profile/password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('profile/password-change/done/', views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/',
         PasswordResetView.as_view(
            template_name="password_reset_form.html",
            email_template_name="password_reset_email.html",
            success_url=reverse_lazy("system_pages:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html",
            success_url=reverse_lazy("system_pages:password_reset_complete")
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),
         name='password_reset_complete'),
]

system_pages/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

from .models import *
from django.core.validators import *

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email']

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль",
                                   widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

system_pages/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render
from valutes.views import CurrencyArticleMixin
from django.views.generic import ListView, DetailView, CreateView, TemplateView, View, FormView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import *

class RegisterUser(CurrencyArticleMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('system_pages:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)



class LoginUser(CurrencyArticleMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)


def logout_user(request):
    logout(request)
    return redirect('/')


class ProfileUser(LoginRequiredMixin, CurrencyArticleMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'profile.html'

    def get_success_url(self):
        return reverse_lazy('system_pages:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)


class UserPasswordChange(CurrencyArticleMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = "password_change_form.html"
    success_url = reverse_lazy("system_pages:password_change_done")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)


class PasswordChangeDoneView(CurrencyArticleMixin, View):
    template_name = "password_change_form.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

system_pages/templates/login.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Авторизация {% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <form method="post">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
            <br>
        {% endfor %}

        <button type="submit">Войти</button>
        <br><br>
        <a href="{% url 'system_pages:password_reset' %}">Забыли пароль?</a>
    </form>
  </div>

{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

system_pages/templates/password_change_done.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Аккаунт {% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
      <h1>Пароль успешно изменен!</h1>
      <p>Вы успешно изменили пароль.</p>
  </div>
{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

system_pages/templates/password_change_form.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Аккаунт {% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <br>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">Изменить пароль</button></p>
    </form>
  </div>

{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

system_pages/templates/password_reset_complete.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Пароль изменен {% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <h1>Пароль изменен</h1>

    <p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
    <a href="{% url 'system_pages:login' %}">входа в систему</a>.</p>
  </div>

{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

system_pages/templates/password_reset_confirm.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Авторизация {% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p><br>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>
  </div>

{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

system_pages/templates/password_reset_done.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Сброс пароля {% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <h1>Сброс пароля</h1>

  <p>Мы отправили вам по электронной почте инструкции по установке пароля, если существует учетная запись с указанным вами адресом электронной почты. Вы должны получить их в ближайшее время.</p>
  <p>Если вы не получили электронное письмо, убедитесь, что вы ввели адрес, под которым зарегистрировались, и проверьте папку со спамом.</p>

{% endblock %}

{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

system_pages/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'system_pages:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

system_pages/templates/password_reset_form.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Восстановление пароля {% endblock %}

{% block main_menu %}
    <li><span><a name="main" title="Мониторинг выгодных курсов от надежных обменников">Главная страница</a></span></li>
    <li><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <h1>Сброс пароля</h1>
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit">Отправить</button></p>
    </form>
  </div>

{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

system_pages/templates/profile.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Аккаунт {% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block info_block %}
    {% if request.user.is_authenticated %}
        <dt><a href="/admin">Админ Панель</a></dt>
        <dt><a href="/system/logout">Выйти</a></dt>
    {% else %}
        <dt><a href="/system/login">Вход</a> | <a href="/system/register">Регистрация</a></dt>
    {% endif %}
    <dt>Последнее обновление:</dt>
    <dd>13:35:37</dd>
{% endblock %}


{% block small_text %}
  <div class="middle-panel">
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p><br>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <br>
    <a href="password-change/">Сменить пароль</a>
    <br>
    <p><button type="submit">Сохранить</button></p>
    </form>
  </div>

{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

system_pages/templates/register.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %} Регистрация {% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <form method="post">
        {% csrf_token %}

        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <br>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <button type="submit">Регистрация</button>
    </form>
  </div>

{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}