my_site/urls.py
from django.urls import path, register_converter, include
from django.http import HttpResponseNotFound
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('valutes/', include('valutes.urls')),
    path('blog/', include('valutesBlog.urls')),
    path('system/', include('system_pages.urls')),
    path('', RedirectView.as_view(url='valutes/', permanent=True)),
    path('', include('valutesBlog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель управления"
admin.site.index_title = "Сайт обзора валют"

valutesBlog/urls.py
from django.urls import path
from . import views

app_name = "valutesBlog"

urlpatterns = [
    path('', views.MainPageView.as_view(), name='blog_index'),
    path('order/<int:order_id>/', views.BlogWithOrderView.as_view(), name='blog_with_order'),
    path('order/lates/', views.BlogLatesView.as_view(), name='blog_lates'),
    path('order/earliest/', views.BlogEarliestView.as_view(), name='blog_earliest'),
    path('order/sort_rating/', views.BlogSortRatingView.as_view(), name='blog_sort_rating'),
    path('post/<slug:post_slug>/', views.ShowArticleView.as_view(), name='post'),
    path('add_article/', views.AddArticleView.as_view(), name='add_article'),
    path('edit/<slug:post_slug>/', views.EditCurrencyArticleView.as_view(), name='edit_article'),
    path('delete/<slug:post_slug>/', views.DeleteCurrencyArticleView.as_view(), name='delete_article'),
]

valutesBlog/models.py
import os
from django.utils import timezone

from django.db import models
from valutes.models import Currency
from django.db.models import Value
from django.db.models import Count
from django.db.models import F
from django.urls import reverse
from django.db.models.functions import Concat, Substr

class DisplayStatus(models.TextChoices):
    CAN_DISPLAY = 'CD', 'Можно отобразить'
    CANNOT_DISPLAY = 'NCD', 'Нельзя отобразить'

class ArticleOrderManager(models.Manager):
    def get_article_orders(self):
        return self.filter(display_status=DisplayStatus.CAN_DISPLAY)

    def get_article_orders_with_article_count(self):
        # Получаем базовый queryset
        queryset = super().get_queryset()
        # Аннотируем количество связанных объектов CurrencyArticle
        queryset = queryset.annotate(articles_count=Count('articles'))
        return queryset

class ArticleOrder(models.Model):
    title = models.CharField(max_length=30, verbose_name='Название')
    displayable_objects = ArticleOrderManager()

    class Meta:
        verbose_name = 'Тег новостей'
        verbose_name_plural = 'Теги новостей'

    def __str__(self):
        return self.title

class CurrencyArticleManager(models.Manager):
    def get_displayable_articles(self):
        return self.annotate(is_active=Value(DisplayStatus.CAN_DISPLAY, output_field=models.CharField())).filter(display_status=DisplayStatus.CAN_DISPLAY)

    def get_articles_by_order_id(self, order_id):
        return self.filter(article_order_id=order_id)

    def get_articles_lates(self):
        return self.order_by('-date')

    def get_articles_earliest(self):
        return self.order_by('date')

    def get_articles_sort_rating(self):
        return self.order_by(F('rating'))




def generate_photo_filename(instance, filename):
    """
    Генерация случайного имени файла для фотографии.
    """
    _, ext = os.path.splitext(filename)
    current_datetime = timezone.now()
    new_filename = f"{current_datetime.strftime('%Y%m%d%H%M%S')}{instance.pk}{ext}"
    return os.path.join("photos", current_datetime.strftime("%Y/%m/%d"), new_filename)

class CurrencyArticle(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    full_text = models.TextField(verbose_name='Полный текст')
    date = models.DateField(verbose_name='Дата публикации')
    display_status = models.CharField(max_length=3, choices=DisplayStatus.choices, default=DisplayStatus.CAN_DISPLAY
                                      ,verbose_name='Статус')

    photo = models.ImageField(upload_to=generate_photo_filename, verbose_name="Фото", null=True)

    article_order = models.ForeignKey(ArticleOrder, on_delete=models.SET_NULL, verbose_name='Тип новости', related_name='articles', null=True)
    currencies = models.ManyToManyField(Currency, verbose_name='Валюты')

    objects = models.Manager()
    displayable_objects = CurrencyArticleManager()

    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL", null=True)

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    @property
    def anons(self):
        # Получаем анонс из первых 250 символов full_text и добавляем троеточие в конце
        return self.full_text[:250] + '...' \
            if len(self.full_text) > 250 \
            else self.full_text

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    def __str__(self):
        return self.title

valutesBlog/forms.py
from django import forms
from .models import *
from django.core.validators import *


def MarksValidator(value):
    exclamation_count = value.count('!')
    question_count = value.count('?')

    if exclamation_count >= 3 or question_count >= 3:
        raise ValidationError("Большое количество восклицательных и вопросительных знаков.")


def TitleCharsValidator(value):
    pattern = re.compile(r'[+=<>{}[\]~`@#$%^&*_\-|\\/\'"\s]')

    if pattern.search(value):
        raise ValidationError("Заголовок содержит недопустимые символы.")

class AddCurrencyArticleForm(forms.ModelForm):

    currencies = forms.ModelMultipleChoiceField(
        queryset=Currency.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(),
        label="Валюты"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['article_order'].empty_label = 'Без статуса'
        self.fields['article_order'].required = False
        self.fields['title'].validators = [MarksValidator]

    class Meta:
        model = CurrencyArticle
        fields = ['title', 'full_text', 'photo', 'article_order', 'currencies', 'display_status', 'slug', 'date']

class EditCurrencyArticleForm(forms.ModelForm):

    currencies = forms.ModelMultipleChoiceField(
        queryset=Currency.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple(),
        label="Валюты"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['article_order'].empty_label = 'Без статуса'
        self.fields['article_order'].required = False
        self.fields['title'].validators = [MarksValidator]

    class Meta:
        model = CurrencyArticle
        fields = ['title', 'full_text', 'photo', 'article_order', 'currencies', 'display_status', 'slug', 'date']

class DeleteCurrencyArticleForm(forms.ModelForm):
    class Meta:
        model = CurrencyArticle
        fields = []

valutesBlog/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
import requests
from bs4 import BeautifulSoup
from django.shortcuts import render
from django.http import HttpResponse
from valutes.models import Currency
from valutesBlog.models import CurrencyArticle
from valutesBlog.models import ArticleOrder
from .forms import *
from valutesBlog.models import CurrencyArticleManager
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, TemplateView, View, FormView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

class CurrencyArticleMixin:
    def get_mixin_context(self, context):
        context['article_orders'] = ArticleOrder.displayable_objects.get_article_orders_with_article_count()
        currencies = Currency.objects.get_currencies()

        half_size = len(currencies) // 2
        currencies_first_half = currencies[:half_size]
        currencies_second_half = currencies[half_size:]

        context['article_orders'] = ArticleOrder.displayable_objects.get_article_orders_with_article_count()
        context['currencies'] = currencies
        context['currencies_first_half'] = currencies_first_half
        context['currencies_second_half'] = currencies_second_half
        return context

class MainPageView(CurrencyArticleMixin, ListView):
    paginate_by = 2

    model = CurrencyArticle
    template_name = 'blog_index.html'
    context_object_name = 'displayable_articles'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

class BlogWithOrderView(CurrencyArticleMixin, ListView):
    paginate_by = 2

    model = CurrencyArticle
    template_name = 'blog_index.html'
    context_object_name = 'displayable_articles'

    def get_queryset(self):
        order_id = self.kwargs['order_id']
        return CurrencyArticle.displayable_objects.get_articles_by_order_id(order_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_id'] = self.kwargs['order_id']
        return self.get_mixin_context(context)


class BlogLatesView(CurrencyArticleMixin, ListView):
    paginate_by = 2

    model = CurrencyArticle
    template_name = 'blog_index.html'
    context_object_name = 'displayable_articles'

    def get_queryset(self):
        return CurrencyArticle.displayable_objects.get_articles_lates()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

class BlogEarliestView(CurrencyArticleMixin, ListView):
    paginate_by = 2

    model = CurrencyArticle
    template_name = 'blog_index.html'
    context_object_name = 'displayable_articles'

    def get_queryset(self):
        return CurrencyArticle.displayable_objects.get_articles_earliest()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

class BlogSortRatingView(CurrencyArticleMixin, ListView):
    paginate_by = 2

    model = CurrencyArticle
    template_name = 'blog_index.html'
    context_object_name = 'displayable_articles'

    def get_queryset(self):
        return CurrencyArticle.displayable_objects.get_articles_sort_rating()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)


class ShowArticleView(CurrencyArticleMixin, DetailView):
    model = CurrencyArticle
    template_name = 'article_show.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        context['post'] = self.object
        return self.get_mixin_context(context)

class AddArticleView(PermissionRequiredMixin, CurrencyArticleMixin, CreateView):
    model = CurrencyArticle
    form_class = AddCurrencyArticleForm
    template_name = 'add_article.html'
    success_url = reverse_lazy('valutesBlog:blog_index')
    permission_required = 'valutesBlog.add_currencyarticle'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['displayable_articles'] = CurrencyArticle.displayable_objects.all()
        return self.get_mixin_context(context)

class EditCurrencyArticleView(PermissionRequiredMixin, CurrencyArticleMixin, UpdateView):
    model = CurrencyArticle
    fields = ['title', 'full_text', 'photo', 'article_order', 'display_status', 'date']
    slug_url_kwarg = 'post_slug'
    template_name = 'edit_article.html'
    success_url = reverse_lazy('valutesBlog:blog_index')
    permission_required = 'valutesBlog.change_currencyarticle'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

class DeleteCurrencyArticleView(CurrencyArticleMixin, DeleteView):
    model = CurrencyArticle
    template_name = 'delete_article.html'
    slug_url_kwarg = 'post_slug'
    success_url = reverse_lazy('currency_article_list')

    def get_object(self):
        _slug = self.kwargs.get('post_slug')
        return get_object_or_404(CurrencyArticle, slug=_slug)

    def get_success_url(self):
        return reverse('valutesBlog:blog_index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

valutesBlog/templates/add_article.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %}Новости{% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li class="active"><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <!-- Панель с кнопками article_orders -->
    <form action="{% url 'valutesBlog:add_article' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>: {{ f }}</p><br>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
      <button type="submit">Добавить</button>
    </form>

  </div>
{% endblock %}


{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

valutesBlog/templates/article_show.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %}Новости{% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li class="active"><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
    {{post.title}}
    {% if perms.valutesBlog.change_currencyarticle %}
        <p><a href="{% url 'valutesBlog:edit_article' post.slug %}">Редактировать</a></p>
    {% endif %}
    {% if post.photo %}
        <p><img class="img-article-left" src="{{ post.photo.url }}"></p>
    {% endif %}
    {{post.full_text}}
{% endblock %}

{% block footer_indent %}
    {% with text_length=post.full_text|length %}
        {% for i in 100|get_range %}
            <br>
        {% endfor %}
    {% endwith %}
{% endblock %}

valutesBlog/templates/blog_index.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %}Новости{% endblock %}


{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    {% if perms.valutesBlog.add_currencyarticle %}
        <li><span><p><a href="{% url 'valutesBlog:add_article' %}">Добавить</a></span></li>
    {% endif %}
    <!-- Панель с новостями-->
    {% if page_obj.has_other_pages %}
        {% if page_obj.has_previous %}
            <li><span><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></span></li>
        {% endif %}
        {% for p in paginator.page_range %}
        {% if page_obj.number == p %}
           <li><span style="color:white">{{ p }}</span></li>
        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
            <li><span><a href="?page={{ p }}">{{ p }}</a></span></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><span><a href="?page={{ page_obj.next_page_number }}">&gt;</a></span></li>
        {% endif %}
    {% endif %}
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <!-- Панель с кнопками article_orders -->
    <div class="button-panel" style="margin-bottom: 10px;">
      {% for order in article_orders %}
        <a href="/blog/order/{{ order.id }}" style="display: inline-block;background-color: #f8f9fa;border: 1px solid #ccc;padding: 5px;margin-right: 5px;color: inherit;text-decoration: none;">{{ order }}({{ order.articles_count }})</a>
      {% endfor %}
        <a href="/blog" class="custom-button-style" style="display: inline-block;background-color: #f8f9fa;border: 1px solid #ccc;padding: 5px;margin-right: 5px;color: inherit;text-decoration: none;">Все новости</a>
    </div>

    <!-- Панель с кнопками сортировки -->
    <div class="button-panel" style="margin-bottom: 10px;">
        <a href="/blog/order/earliest/" style="display: inline-block;background-color: #f8f9fa;border: 1px solid #ccc;padding: 5px;margin-right: 5px;color: inherit;text-decoration: none;">Самые ранние</a>
        <a href="/blog/order/lates/" class="custom-button-style" style="display: inline-block;background-color: #f8f9fa;border: 1px solid #ccc;padding: 5px;margin-right: 5px;color: inherit;text-decoration: none;">Самые поздние</a>
    </div>

    <!-- Панель с кнопками сортировки -->
    <div class="button-panel" style="margin-bottom: 10px;">
        <a href="/blog/order/sort_rating/" style="display: inline-block;background-color: #f8f9fa;border: 1px solid #ccc;padding: 5px;margin-right: 5px;color: inherit;text-decoration: none;">Сортировать по рейтингу</a>
    </div>

  <!-- Панели новостей -->
  <div id="info_news">
      {% for article in displayable_articles %}
      <div class="news-container" style="overflow: auto; max-height: 500px;">
        <div class="news-panel" style="margin-bottom: 10px; padding: 10px; border: 1px solid #ccc;">
            <div class="inner">
                <dl><dt><small>{{ article.date|date:"Y-m-d" }}</small> {{ article.title }}</dt>
                  {% if article.article_order %}
                    <p style="text-align: left;">
                        <small>{{ article.article_order }}</small>
                    </p>
                  {% endif %}
                  {% if article.currencies.exists %}
                    <p style="text-align: left;">
                        <small>{{ article.currencies.all|join:", " }}</small>
                    </p>
                  {% endif %}
                <dd><p>{{ article.anons }}</p></dd>
                </dl>
                <a href="/blog/post/{{ article.slug }}" style="display: inline-block;background-color: #f8f9fa;border: 1px solid #ccc;padding: 5px;margin-right: 5px;color: inherit;text-decoration: none;">Читать</a>
            </div>
            </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block footer_indent %}
    {% for article in displayable_articles %}
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    {% endfor %}
{% endblock %}

valutesBlog/templates/delete_article.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %}Новости{% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li class="active"><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <!-- Панель с кнопками article_orders -->
    <form method="post" enctype="multipart/form-data">
        <h1>Вы уверены, что хотите удалить публикацию ?</h1>>
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Да"/> <a href="../">Отмена</a></p>>
    </form>
  </div>
{% endblock %}

{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}

valutesBlog/templates/edit_article.html
{% extends "index_base.html" %}
{% load custom_tags %}

{% block title %}Новости{% endblock %}

{% block main_menu %}
    <li><span><a href="/valutes" title="Главная страниц сайта">Главная страница</a></span></li>
    <li class="active"><span><a href="/blog" title="Список всех новостей">Новости</a></span></li>
    <li><span><a href="/valutes/about_company" title="Информация о компании">О компании</a></span></li>
    <li><span><a href="/valutes/faq" title="Ответы на часто задаваемые вопросы">FAQ</a></span></li>
    <li><span><a href="/valutes/about_site" title="Информация о сайте">О сайте</a></span></li>
{% endblock %}

{% block small_text %}
  <div class="middle-panel">
    <!-- Панель с кнопками article_orders -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
      <button type="submit">Редактировать</button>
    </form>
  </div>
{% endblock %}

{% block footer_indent %}
    {% for i in 30|get_range %}
        <br>
    {% endfor %}
{% endblock %}